apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    {{- include "app.Labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80         # service监听的端口
      targetPort: 8000 # 在Service资源中定义的，用于指定将流量转发到的目标端口
      nodePort: 32628  # 固定nodeport端口（默认随机生成）
  type: NodePort
