server:
  http:
    addr: :8000
    timeout: 1s
  grpc:
    addr: :9000
    timeout: 1s
data:
  database:
    driver: mysql
    # source: root:root@tcp(mysql-service:3306)/demo  deployment资源访问模式
    source: root:root@tcp(mysql-service.default.svc.cluster.local:3306)/demo 

