// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: callMysql.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callMysql_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callMysql_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_callMysql_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CallReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CallReply) Reset() {
	*x = CallReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_callMysql_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallReply) ProtoMessage() {}

func (x *CallReply) ProtoReflect() protoreflect.Message {
	mi := &file_callMysql_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallReply.ProtoReflect.Descriptor instead.
func (*CallReply) Descriptor() ([]byte, []int) {
	return file_callMysql_proto_rawDescGZIP(), []int{1}
}

func (x *CallReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_callMysql_proto protoreflect.FileDescriptor

var file_callMysql_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x61, 0x6c, 0x6c, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x0b, 0x43, 0x61,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x09, 0x43, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x32, 0x5b, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x50, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x12, 0x16, 0x2e, 0x63, 0x61,
	0x6c, 0x6c, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0c, 0x12, 0x0a, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x1a, 0x0a,
	0x03, 0x61, 0x70, 0x69, 0x50, 0x01, 0x5a, 0x11, 0x63, 0x61, 0x6c, 0x6c, 0x4d, 0x79, 0x73, 0x71,
	0x6c, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_callMysql_proto_rawDescOnce sync.Once
	file_callMysql_proto_rawDescData = file_callMysql_proto_rawDesc
)

func file_callMysql_proto_rawDescGZIP() []byte {
	file_callMysql_proto_rawDescOnce.Do(func() {
		file_callMysql_proto_rawDescData = protoimpl.X.CompressGZIP(file_callMysql_proto_rawDescData)
	})
	return file_callMysql_proto_rawDescData
}

var file_callMysql_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_callMysql_proto_goTypes = []interface{}{
	(*CallRequest)(nil), // 0: callMysql.CallRequest
	(*CallReply)(nil),   // 1: callMysql.CallReply
}
var file_callMysql_proto_depIdxs = []int32{
	0, // 0: callMysql.Greeter.GetMysqlMess:input_type -> callMysql.CallRequest
	1, // 1: callMysql.Greeter.GetMysqlMess:output_type -> callMysql.CallReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_callMysql_proto_init() }
func file_callMysql_proto_init() {
	if File_callMysql_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_callMysql_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_callMysql_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_callMysql_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_callMysql_proto_goTypes,
		DependencyIndexes: file_callMysql_proto_depIdxs,
		MessageInfos:      file_callMysql_proto_msgTypes,
	}.Build()
	File_callMysql_proto = out.File
	file_callMysql_proto_rawDesc = nil
	file_callMysql_proto_goTypes = nil
	file_callMysql_proto_depIdxs = nil
}
